development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  timeout: 5000

staging: 
  adapter: postgresql
  encoding: unicode
  database: store_staging
  pool: 5
  timeout: 5000
